# Generated by Django 3.2.7 on 2021-10-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='relator',
            new_name='realtor',
        ),
    ]
